---
- name: launch ansible cloudformation template
  cloudformation:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    stack_name: "orezi-cloudformation"
    state: "present"
    region: "us-east-1"
    disable_rollback: true
    template: "cloudformation.template"
    tags:
      Stack: "orezi-cloudformation"
  register: cloudformation