---
- name: launch ansible cloudformation template
  cloudformation:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    stack_name: "{{ cloudformation_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "cloudformation.template"
    tags:
      Stack: "{{ cloudformation_name }}"
  register: cloudformation