---
- name: create launch config
  ec2_lc:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    name: orezi-lc
    region: "us-east-1"
    image_id: "{{ instance.image_id }}"
    state: present
    instance_type: t2.micro