---
- name: check if autoscaling group exists
  command: bash -c "aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name {{ autoscaling_grp }} | grep {{ autoscaling_grp }}"
  register: asg_exists
  ignore_errors: true

- name: create autoscaling group
  when: asg_exists|failed
  ec2_asg:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    name: "{{ autoscaling_grp }}"
    region: "{{ region }}"
    launch_config_name: "{{ launch_cfg_name }}"
    state: present
    min_size: 1
    max_size: 3
    desired_capacity: 1
    wait_for_instances: no
    tags:
      - environment: practice