---
- name: create machine image
  ec2_ami:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    instance_id: "{{cloudformation.stack_resources[2].physical_resource_id}}"
    wait: yes
    name: orezi-ami
    state: present 
    region: "us-east-1"
    tags:
      Name: orezi-ami
      Service: test
  register: instance